apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql2
  labels:
    app: wordpress2
spec:
  ports:
    - port: 3307
  selector:
    app: wordpress2
    tier: mysql2
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim2
  labels:
    app: wordpress2
  annotations: 
    volume.beta.kubernetes.io/storage-class: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-mysql2
  labels:
    app: wordpress2
spec:
  selector:
    matchLabels:
      app: wordpress2
      tier: mysql2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress2
        tier: mysql2
    spec:
      containers:
      - image: mysql:5.6
        name: mysql2
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3307
          name: mysql2
        volumeMounts:
        - name: mysql-persistent-storage2
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage2
        persistentVolumeClaim:
          claimName: mysql-pv-claim2
