apiVersion: v1
kind: Service
metadata:
  name: wordpress2
  labels:
    app: wordpress2
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30332
  selector:
    app: wordpress2
    tier: frontend2
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim2
  labels:
    app: wordpress2
  annotations:
    volume.beta.kubernetes.io/storage-class: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress2
  labels:
    app: wordpress2
spec:
  selector:
    matchLabels:
      app: wordpress2
      tier: frontend2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress2
        tier: frontend2
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress2
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql2
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress2
        volumeMounts:
        - name: wordpress-persistent-storage2
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage2
        persistentVolumeClaim:
          claimName: wp-pv-claim2
